language: ruby
services:
  - redis-server
rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-20mode
  - jruby-21mode
gemfile:
  - gemfiles/rails_31.gemfile
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
script: bundle exec rake test

matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_40.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_41.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_31.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_32.gemfile
